# Generated by Django 5.0.1 on 2024-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("id_number", models.CharField(max_length=50, unique=True)),
                ("unique_id", models.CharField(max_length=100, unique=True)),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("area_deed", models.IntegerField()),
                ("area_survey", models.IntegerField()),
                ("coordinate", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("hay", models.CharField(blank=True, max_length=100)),
                ("subdivision_number", models.CharField(blank=True, max_length=50)),
                ("neighborhood", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("type_of_transaction", models.CharField(max_length=100)),
                ("ownership_transfer", models.BooleanField(default=False)),
                ("merge_land_parcels", models.BooleanField(default=False)),
                ("split_land_parcel", models.BooleanField(default=False)),
                ("hash_reference", models.CharField(max_length=255)),
                ("registration_authority_court", models.CharField(max_length=150)),
                ("registration_authority_date", models.DateField()),
                ("registration_authority_decision", models.CharField(max_length=200)),
            ],
        ),
    ]
