# Generated by Django 5.0.1 on 2024-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_landownershipdata_land"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyLandLocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("info", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MyStreetlightModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("details", models.CharField(max_length=255)),
            ],
        ),
    ]
